name: publish-to-pypi.yaml

on:
  push:
    tags:
      - 0*

jobs:
  run:
    runs-on: ubuntu-latest

    environment:
      name: pypi

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      - name: Print Python version
        run: |
          python --version

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint and test code
        run: |
          make clean check-lock-file lint test coverage

      - name: Build
        run: make build

      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/test_whitespace_format.py

      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/test_whitespace_format.py

      - name: Publish
        run: uv publish
